version: "3.8"

networks:
  cortex-net:

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: cortex
      POSTGRES_PASSWORD: ${CORTEX_DB_PASSWORD}
      POSTGRES_DB: cortex
    volumes:
      - cortex_pgdata:/var/lib/postgresql/data
    networks:
      - cortex-net

  api:
    build: ../services/api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://cortex:${CORTEX_DB_PASSWORD}@postgres:5432/cortex
      CORTEX_API_KEY: ${CORTEX_API_KEY}                    # NEW
      PROMETHEUS_FILE_SD_PATH: /file_sd/nodes.json          # NEW
    volumes:
      - ../services/api:/app
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - cortex-net

volumes:
  cortex_pgdata:
  - cortex_file_sd:/file_sd 