"""OpenStack Expert Agent (v0.6, docs/architecture/adr-0008-openstack-
expert-agent.md) -- "the system starts teaching, not just reporting."

Every prior agent reports a finding (a number, a flagged metric, a
correlated log line). This agent's job is different: given a finding, or
given a direct question, it looks up the matching entry in
openstack_expert_catalog.CATALOG and answers with the fixed 3-layer shape
every entry is authored in:

1. **What's happening** -- the general mechanism behind this symptom
   (`entry["what_it_means"]`), prefixed with the concrete evidence that
   triggered it when there is any (a specific metric value, a specific log
   line) so the answer teaches the *general* pattern while staying
   anchored to *this* incident.
2. **How to confirm it yourself** -- `entry["confirm_commands"]`, always
   read-only, always rendered verbatim (never paraphrased or generated by
   an LLM -- an operational command is either exactly correct or actively
   harmful to trust, there's no room for a fluent-but-wrong version).
3. **What's usually done about it** -- `entry["remediation_commands"]`, a
   mix of read-only and state-changing, each labeled explicitly.

Two ways into this agent, distinguished by what's already in `state` when
it runs (see graph.py):

- **Chained**: routed here automatically straight after anomaly_agent or
  monitoring_agent produced a real finding (see should_trigger_after_
  anomaly/should_trigger_after_monitoring, which graph.py's conditional
  edges call). `state["target_agent"]` is still "anomaly" or "monitoring"
  at that point -- this agent reads that to know it's chained, and to know
  which upstream `raw_data` shape to pull evidence from, then overwrites
  `target_agent` to "openstack_expert" once it has produced its own
  result (the original diagnosis's `raw_data` is nested under
  `diagnosed_by`/`upstream_summary` in the new result, never discarded).
- **Standalone**: routed here directly by the router for a direct
  "how do I check X" / "how do I fix Y" question with no upstream
  diagnosis -- `state["target_agent"]` is already "openstack_expert" on
  entry, set by intent_router.py, and there is no `agent_result` yet.

Both paths converge on the same `_match_symptoms` -> `_render_answer`
pipeline; only how the matcher's inputs (metric name, service binaries,
free-text keywords, log line content) get assembled differs.
"""
import logging
import re

from ..node_resolver import resolve_node
from ..state import CortexState
from .openstack_expert_catalog import CATALOG, SymptomEntry

logger = logging.getLogger(__name__)

# Built from the catalog itself (not hand-duplicated) so a new entry's
# service_binaries automatically become recognizable in free text without
# a second list to keep in sync.
_ALL_SERVICE_BINARIES = sorted({b for entry in CATALOG for b in entry["service_binaries"]})

# A live/monitoring metric has to clear this before it's worth treating as
# "the thing to explain" rather than normal variation -- same threshold
# anomaly.py's own live-read fallback and monitoring's system prompt use
# ("call out anything above ~90%"), kept slightly under that so the expert
# agent still fires on a monitoring-flagged "concerning" reading.
_METRIC_TRIGGER_THRESHOLD = 85.0

# Score weights for the symptom matcher -- a metric-name or service-binary
# hit is a structured, unambiguous signal (worth more) than a keyword
# appearing somewhere in free text, and a keyword in the *question itself*
# is worth more than the same keyword merely appearing in a log line (the
# latter is corroborating, not the actual ask).
_SCORE_METRIC_NAME = 3
_SCORE_SERVICE_BINARY = 3
_SCORE_KEYWORD_IN_QUERY = 2
# Weighted equal to a query-keyword hit, not lower: a keyword actually
# found in real log content is concrete corroborating evidence, not a
# guess -- and this is what lets a specific log pattern (e.g. "lost
# connection to libvirt") outrank a bare metric-name match (e.g.
# "cpu_usage") when both are present, matching anomaly.py's own
# _hypothesize_cause philosophy that log content is the more specific
# signal when it's available.
_SCORE_KEYWORD_IN_LOG_LINE = 2

# Placeholders in catalog commands that are safe to fill in with a
# concretely-known hostname -- anything else (<instance_id>, <volume_id>,
# <agent_id>, ...) is left as a placeholder since this agent never has
# that specific a value on hand.
_HOST_PLACEHOLDERS = re.compile(r"<host>|<hostname>|<hypervisor_hostname>")


# --------------------------------------------------------------------
# Symptom matcher
# --------------------------------------------------------------------

def _match_symptoms(
    *,
    metric_name: str | None = None,
    service_binaries: list[str] | None = None,
    query: str = "",
    log_lines: list[str] | None = None,
) -> list[tuple[SymptomEntry, int]]:
    """Every catalog entry with a positive score, most-relevant first.
    Ties keep CATALOG's own order (Python sort is stable) -- CATALOG is
    already ordered most-likely-to-fire-first per its module docstring, so
    that's a reasonable tiebreak, not an arbitrary one.
    """
    service_binaries = service_binaries or []
    log_lines = log_lines or []
    query_lower = query.lower()
    log_lower = [line.lower() for line in log_lines]

    scored: list[tuple[SymptomEntry, int]] = []
    for entry in CATALOG:
        score = 0
        if metric_name and metric_name in entry["metric_names"]:
            score += _SCORE_METRIC_NAME
        if any(b in entry["service_binaries"] for b in service_binaries):
            score += _SCORE_SERVICE_BINARY
        for keyword in entry["keywords"]:
            if keyword in query_lower:
                score += _SCORE_KEYWORD_IN_QUERY
            if any(keyword in line for line in log_lower):
                score += _SCORE_KEYWORD_IN_LOG_LINE
        if score > 0:
            scored.append((entry, score))

    scored.sort(key=lambda pair: -pair[1])
    return scored


def _detect_service_binaries(text: str) -> list[str]:
    text_lower = text.lower()
    return [b for b in _ALL_SERVICE_BINARIES if b in text_lower or b.replace("-", " ") in text_lower]


# --------------------------------------------------------------------
# Evidence extraction from an upstream diagnosis (chained mode)
# --------------------------------------------------------------------

def _dominant_metric_from_live_data(data: dict) -> str | None:
    """Same "which resource is actually hot" logic as anomaly.py's
    _hypothesize_cause live-threshold tier, reused here because both need
    the same answer to the same question from the same shape of data."""
    candidates = [
        (data.get("cpu_percent", 0.0), "cpu_usage"),
        (data.get("memory_percent", 0.0), "ram_usage"),
        (data.get("disk_percent", 0.0), "disk_usage"),
    ]
    value, name = max(candidates, key=lambda c: c[0])
    return name if value >= _METRIC_TRIGGER_THRESHOLD else None


def _evidence_from_anomaly(raw_data: dict) -> dict:
    metric_signal = raw_data.get("metric_signal") or {}
    log_signal = raw_data.get("log_signal") or {}
    data = metric_signal.get("data") or {}

    metric_name = None
    if metric_signal.get("has_signal"):
        if data.get("source") == "anomaly_flags":
            metric_name = data.get("metric_name")
        else:
            metric_name = _dominant_metric_from_live_data(data)

    log_lines = [e["line"] for e in log_signal.get("entries", [])]
    combined_text = " ".join(log_lines) + " " + (raw_data.get("likely_cause") or "")
    service_binaries = _detect_service_binaries(combined_text)

    evidence_sentences = [metric_signal.get("detail", "")]
    if log_signal.get("has_signal") or log_signal.get("degraded"):
        evidence_sentences.append(log_signal.get("detail", ""))

    return {
        "metric_name": metric_name,
        "service_binaries": service_binaries,
        "log_lines": log_lines,
        "evidence_line": " ".join(s for s in evidence_sentences if s),
        "hostname": raw_data.get("hostname"),
    }


def _evidence_from_monitoring(raw_data: dict) -> dict:
    metrics = raw_data
    if metrics.get("status") != "up":
        # Sentinel matched by the "node-unreachable" catalog entry's own
        # metric_names -- see that entry's comment. A dead host isn't "a
        # resource reading high", it's a different symptom entirely, so
        # this deliberately doesn't fall through to _dominant_metric_from_
        # live_data (which would just see all-zero readings and match
        # nothing, or worse, something misleading).
        metric_name = "host_down"
    else:
        metric_name = _dominant_metric_from_live_data(metrics)

    evidence_line = (
        f"{metrics.get('node', 'this host')} is currently at {metrics.get('cpu_percent')}% CPU, "
        f"{metrics.get('memory_percent')}% RAM, {metrics.get('disk_percent')}% disk -- "
        f"status {metrics.get('status')} ({metrics.get('health')})."
    )
    return {
        "metric_name": metric_name,
        "service_binaries": [],
        "log_lines": [],
        "evidence_line": evidence_line,
        "hostname": metrics.get("node"),
    }


def should_trigger_after_anomaly(state: CortexState) -> bool:
    """Whether anomaly_agent's result has anything for this agent to
    explain -- called from graph.py's conditional edge, and mirrors what
    this module's own chained path checks internally (see
    _evidence_from_anomaly / the "no positive match" fallback in
    _run_chained) so a "yes, chain" decision here is never followed by
    "actually, nothing to say" once inside the node.
    """
    if state.get("error") or not state.get("agent_result"):
        return False
    raw_data = state["agent_result"]["raw_data"]
    metric_signal = raw_data.get("metric_signal") or {}
    log_signal = raw_data.get("log_signal") or {}
    return bool(metric_signal.get("has_signal") or log_signal.get("has_signal") or log_signal.get("degraded"))


def should_trigger_after_monitoring(state: CortexState) -> bool:
    """Whether monitoring_agent's live read looks concerning enough to
    walk through -- same "status not up, health not healthy" bar
    monitoring's own system prompt already uses for "call this out", so
    chaining fires exactly when a human reading the monitoring answer
    would already feel like something's wrong.
    """
    if state.get("error") or not state.get("agent_result"):
        return False
    metrics = state["agent_result"]["raw_data"]
    return metrics.get("status") != "up" or metrics.get("health") != "healthy"


# --------------------------------------------------------------------
# Rendering: SymptomEntry -> the fixed 3-layer answer text
# --------------------------------------------------------------------

def _fill_hostname(command: str, hostname: str | None) -> str:
    if not hostname:
        return command
    return _HOST_PLACEHOLDERS.sub(hostname, command)


def _render_command_list(commands: list[dict], hostname: str | None) -> str:
    """Renders each command as its own bullet, with the description as the
    bullet's lead-in and the command itself in a fenced ```bash block --
    the fence is what actually gets the client's markdown renderer to draw
    a proper copyable code block instead of one long inline-code line, and
    the (read-only)/(state-changing) label stays plain text (not inside
    the fence) so it's still readable as a UI-parseable tag rather than
    part of the shell command."""
    blocks = []
    for cmd in commands:
        label = "read-only" if cmd["read_only"] else "state-changing"
        command_text = _fill_hostname(cmd["command"], hostname)
        blocks.append(
            f"- **{cmd['description']}** _({label})_\n"
            f"  ```bash\n"
            f"  {command_text}\n"
            f"  ```"
        )
    return "\n".join(blocks)


def _render_answer(entry: SymptomEntry, evidence_line: str, hostname: str | None) -> str:
    what_happening = f"{evidence_line} {entry['what_it_means']}".strip()
    confirm_block = _render_command_list(entry["confirm_commands"], hostname)
    remediate_block = _render_command_list(entry["remediation_commands"], hostname)

    return (
        f"### {entry['title']}\n\n"
        f"#### What's happening\n{what_happening}\n\n"
        f"#### How to confirm it yourself\n{confirm_block}\n\n"
        f"#### What's usually done about it\n{remediate_block}\n\n"
        f"---\n"
        f"**Deeper reference:** {entry['doc_ref']}"
    )


def _no_match_standalone_answer(query: str) -> str:
    return (
        "I don't have a specific runbook entry that matches that yet. The OpenStack Expert "
        "catalog currently covers:\n\n"
        "- Host resource pressure (CPU / RAM / disk)\n"
        "- The core Nova, Cinder, and Neutron service agents\n"
        "- libvirt / hypervisor issues\n"
        "- RabbitMQ, MariaDB, and Keystone problems\n"
        "- Glance image issues\n\n"
        "Try naming the specific symptom or service (e.g. \"nova-compute\", \"neutron-l3-agent\", "
        "\"disk full\"), or ask it as a general documentation question and I'll search the "
        "knowledge base instead."
    )


def _to_command_dicts(commands: list[dict], hostname: str | None) -> list[dict]:
    """The same commands rendered into `summary`, structured for raw_data
    so a frontend can render read-only/state-changing distinctly (an icon,
    a confirmation dialog before copying a state-changing one) without
    re-parsing the markdown."""
    return [
        {**cmd, "command": _fill_hostname(cmd["command"], hostname)}
        for cmd in commands
    ]


def _build_result(entry: SymptomEntry, evidence_line: str, hostname: str | None, extra_raw: dict) -> dict:
    return {
        "summary": _render_answer(entry, evidence_line, hostname),
        "confidence": 0.85 if evidence_line else 0.6,
        "raw_data": {
            "matched_symptom_id": entry["id"],
            "matched_symptom_title": entry["title"],
            "category": entry["category"],
            "confirm_commands": _to_command_dicts(entry["confirm_commands"], hostname),
            "remediation_commands": _to_command_dicts(entry["remediation_commands"], hostname),
            "doc_ref": entry["doc_ref"],
            **extra_raw,
        },
    }


# --------------------------------------------------------------------
# The two entry paths
# --------------------------------------------------------------------

def _run_chained(state: CortexState, upstream: str) -> CortexState:
    upstream_result = state["agent_result"]
    raw_data = upstream_result["raw_data"]

    if upstream == "anomaly":
        evidence = _evidence_from_anomaly(raw_data)
    else:
        evidence = _evidence_from_monitoring(raw_data)

    matches = _match_symptoms(
        metric_name=evidence["metric_name"],
        service_binaries=evidence["service_binaries"],
        query=state["user_query"],
        log_lines=evidence["log_lines"],
    )

    if not matches:
        # should_trigger_after_* already confirmed there's *something*
        # anomalous, but nothing in the catalog recognizes this specific
        # pattern -- leave the upstream diagnosis as the answer rather
        # than forcing a generic, unhelpful "teaching" layer on top of it.
        logger.info(
            "openstack_expert: chained from %s but no catalog entry matched, "
            "leaving upstream diagnosis as the final answer", upstream,
        )
        return state

    entry, _score = matches[0]
    result = _build_result(
        entry,
        evidence["evidence_line"],
        evidence["hostname"],
        extra_raw={"diagnosed_by": upstream, "upstream_summary": upstream_result["summary"]},
    )
    state["agent_result"] = result
    state["target_agent"] = "openstack_expert"
    return state


def _run_standalone(state: CortexState) -> CortexState:
    query = state["user_query"]
    known_nodes = state.get("known_nodes") or []

    service_binaries = _detect_service_binaries(query)
    matches = _match_symptoms(query=query, service_binaries=service_binaries)

    # Best-effort only -- a standalone "how do I check nova-compute"
    # question doesn't need a specific host, but if one's clearly named
    # (the same resolver every other agent uses), commands get filled in
    # with it rather than left as a placeholder.
    node = resolve_node(query, known_nodes) if known_nodes else None
    hostname = node["hostname"] if node else None

    if not matches:
        state["agent_result"] = {
            "summary": _no_match_standalone_answer(query),
            "confidence": 0.2,
            "raw_data": {"matched_symptom_id": None, "query": query},
        }
        state["error"] = None
        return state

    entry, _score = matches[0]
    result = _build_result(entry, evidence_line="", hostname=hostname, extra_raw={"diagnosed_by": None})
    state["agent_result"] = result
    state["error"] = None
    return state


def openstack_expert_agent(state: CortexState) -> CortexState:
    upstream = state.get("target_agent")
    if upstream in ("anomaly", "monitoring") and state.get("agent_result") and not state.get("error"):
        return _run_chained(state, upstream)
    return _run_standalone(state)
