"""OpenStack Expert Agent (v0.6, docs/architecture/adr-0008-openstack-
expert-agent.md) -- "the system starts teaching, not just reporting."

Every prior agent reports a finding (a number, a flagged metric, a
correlated log line). This agent's job is different: given a finding, or
given a direct question, it looks up the matching entry in
openstack_expert_catalog.CATALOG and answers with the fixed 3-layer shape
every entry is authored in:

1. **What's happening** -- the general mechanism behind this symptom
   (`entry["what_it_means"]`), prefixed with the concrete evidence that
   triggered it when there is any (a specific metric value, a specific log
   line) so the answer teaches the *general* pattern while staying
   anchored to *this* incident.
2. **How to confirm it yourself** -- `entry["confirm_commands"]`, always
   read-only, always rendered verbatim (never paraphrased or generated by
   an LLM -- an operational command is either exactly correct or actively
   harmful to trust, there's no room for a fluent-but-wrong version).
3. **What's usually done about it** -- `entry["remediation_commands"]`, a
   mix of read-only and state-changing, each labeled explicitly.

Two ways into this agent, distinguished by what's already in `state` when
it runs (see graph.py):

- **Chained**: routed here automatically straight after anomaly_agent,
  monitoring_agent, or (v0.9) network_agent produced a real finding (see
  should_trigger_after_anomaly/should_trigger_after_monitoring/
  should_trigger_after_network, which graph.py's conditional edges call).
  `state["target_agent"]` is still "anomaly"/"monitoring"/"network" at
  that point -- this agent reads that to know it's chained, and to know
  which upstream `raw_data` shape to pull evidence from, then overwrites
  `target_agent` to "openstack_expert" once it has produced its own
  result (the original diagnosis's `raw_data` is nested under
  `diagnosed_by`/`upstream_summary` in the new result, never discarded).
- **Standalone**: routed here directly by the router for a direct
  "how do I check X" / "how do I fix Y" question with no upstream
  diagnosis -- `state["target_agent"]` is already "openstack_expert" on
  entry, set by intent_router.py, and there is no `agent_result` yet.

Both paths converge on the same `_match_symptoms` -> `_render_answer`
pipeline; only how the matcher's inputs (metric name, service binaries,
free-text keywords, log line content) get assembled differs.

v0.9 adds a third chaining source: network_agent (nodes/network.py). Its
finding's `raw_data["neutron_signal"]["down_agents"]` maps straight onto
`service_binaries` (a Neutron agent's `binary`, e.g. "neutron-l3-agent"),
which is exactly what the catalog's neutron-dhcp-agent-down/
neutron-l3-agent-down/neutron-ovs-agent-down entries already match on --
those entries existed since before this agent had any live trigger for
them (openstack_expert_catalog.py ships with every service-agent entry
up front), so this is purely a new `_evidence_from_*` extractor plus one
more `should_trigger_after_*` gate, no new catalog content.

v0.10 (Phase C) widens that same network_agent chaining source: its
finding can now come from an entity-scoped read (a network/subnet/
instance question, not a node one -- see nodes/network.py's own v0.10
note) with no Neutron *agent* involved at all, so `_evidence_from_network`
now also recognizes a down/disabled Neutron port and an instance stuck in
ERROR alongside one, via the two new catalog entries (`port-down`,
`instance-stuck-in-error`) this version adds.

v1.0 (docs/architecture/adr-0010-openstack-expert-v1-expansion.md) adds
two things, both scoped to what the original v0.6/v0.9/v0.10 design left
as explicit follow-ups (adr-0008 §OS.4-OS.6):

- **The matcher's `catalog` is no longer just the static CATALOG list.**
  `_combined_catalog` appends every currently-"published" feedback-loop
  entry (agents/nodes/openstack_expert_catalog_store.py, backed by
  models.CatalogEntry) on every call, so an incident type that got
  resolved and turned into a catalog entry from the UI now matches the
  next time it recurs -- chained or standalone -- without a code change
  or a restart. `_match_symptoms`/`_detect_service_binaries` both take an
  explicit `catalog` argument (default: just the static CATALOG, so
  every v0.6-era direct unit test of either function is unaffected).
- **Standalone no-match now falls through two more tiers** before giving
  up (`_standalone_fallback`): official OpenStack documentation
  (services/openstack_docs/search.py, a separate Qdrant collection from
  both this catalog and the internal RAG/Knowledge Agent's own corpus --
  see that module's docstring) and, below that, a community web search
  (services/web_search.py, biased toward Launchpad/mailing-list/Q&A
  sources). Each tier is visibly labeled by source ("catalog" /
  "official_docs" / "web_search" / "none" in `raw_data["source"]`, and in
  the rendered markdown itself) so nobody mistakes a Launchpad forum post
  for either this deployment's curated catalog or actual upstream docs.
  Deliberately standalone-only: a *chained* no-match still leaves the
  upstream diagnosis as the final answer unmodified (see `_run_chained`'s
  own comment) -- that v0.6 decision (adr-0008 decision #4) is preserved
  as-is here, not widened, since a good specific diagnosis still beats a
  generic-but-sourced layer stacked on top of it.
"""
import logging
import re

from ..node_resolver import resolve_node
from ..state import CortexState
from .openstack_expert_catalog import CATALOG, SymptomEntry
from .openstack_expert_catalog_store import load_published_entries

# Imported as plain module-level names (rather than reached for through a
# package prefix at call time) specifically so tests can
# `monkeypatch.setattr(expert, "search_official_docs", ...)` /
# `monkeypatch.setattr(expert, "run_web_search", ...)` the same way
# rag.py's own tests monkeypatch its embed_query/qdrant_search imports --
# see tests/test_openstack_expert.py's v1.0 fallback tests.
from ...services.openstack_docs.format import clean_inline, doc_text_to_markdown, looks_like_index
from ...services.openstack_docs.search import DocResult, search_official_docs
from ...services.web_search import WebSearchResult, search as run_web_search

logger = logging.getLogger(__name__)

# Built from the catalog itself (not hand-duplicated) so a new entry's
# service_binaries automatically become recognizable in free text without
# a second list to keep in sync.
_ALL_SERVICE_BINARIES = sorted({b for entry in CATALOG for b in entry["service_binaries"]})

# A live/monitoring metric has to clear this before it's worth treating as
# "the thing to explain" rather than normal variation -- same threshold
# anomaly.py's own live-read fallback and monitoring's system prompt use
# ("call out anything above ~90%"), kept slightly under that so the expert
# agent still fires on a monitoring-flagged "concerning" reading.
_METRIC_TRIGGER_THRESHOLD = 85.0

# Score weights for the symptom matcher -- a metric-name or service-binary
# hit is a structured, unambiguous signal (worth more) than a keyword
# appearing somewhere in free text, and a keyword in the *question itself*
# is worth more than the same keyword merely appearing in a log line (the
# latter is corroborating, not the actual ask).
_SCORE_METRIC_NAME = 3
_SCORE_SERVICE_BINARY = 3
_SCORE_KEYWORD_IN_QUERY = 2
# Weighted equal to a query-keyword hit, not lower: a keyword actually
# found in real log content is concrete corroborating evidence, not a
# guess -- and this is what lets a specific log pattern (e.g. "lost
# connection to libvirt") outrank a bare metric-name match (e.g.
# "cpu_usage") when both are present, matching anomaly.py's own
# _hypothesize_cause philosophy that log content is the more specific
# signal when it's available.
_SCORE_KEYWORD_IN_LOG_LINE = 2

# Placeholders in catalog commands that are safe to fill in with a
# concretely-known hostname -- anything else (<instance_id>, <volume_id>,
# <agent_id>, ...) is left as a placeholder since this agent never has
# that specific a value on hand.
_HOST_PLACEHOLDERS = re.compile(r"<host>|<hostname>|<hypervisor_hostname>")


# --------------------------------------------------------------------
# Symptom matcher
# --------------------------------------------------------------------

def _match_symptoms(
    *,
    metric_name: str | None = None,
    service_binaries: list[str] | None = None,
    query: str = "",
    log_lines: list[str] | None = None,
    catalog: list[SymptomEntry] | None = None,
) -> list[tuple[SymptomEntry, int]]:
    """Every catalog entry with a positive score, most-relevant first.
    Ties keep the catalog's own order (Python sort is stable) -- CATALOG
    is already ordered most-likely-to-fire-first per its module
    docstring, so that's a reasonable tiebreak, not an arbitrary one; any
    dynamic entries (v1.0, see `catalog` below) are appended after it by
    `_combined_catalog`, so a hand-authored entry still wins a tie over a
    UI-submitted one covering the same symptom.

    `catalog` defaults to just the static CATALOG -- every v0.6-era direct
    call site (including this module's own unit tests) that doesn't pass
    one gets exactly the old, fully offline, fully deterministic behavior.
    `openstack_expert_agent` (v1.0) passes `_combined_catalog()`, which
    also folds in every currently-published feedback-loop entry.
    """
    catalog = catalog if catalog is not None else CATALOG
    service_binaries = service_binaries or []
    log_lines = log_lines or []
    query_lower = query.lower()
    log_lower = [line.lower() for line in log_lines]

    scored: list[tuple[SymptomEntry, int]] = []
    for entry in catalog:
        score = 0
        if metric_name and metric_name in entry["metric_names"]:
            score += _SCORE_METRIC_NAME
        if any(b in entry["service_binaries"] for b in service_binaries):
            score += _SCORE_SERVICE_BINARY
        for keyword in entry["keywords"]:
            if keyword in query_lower:
                score += _SCORE_KEYWORD_IN_QUERY
            if any(keyword in line for line in log_lower):
                score += _SCORE_KEYWORD_IN_LOG_LINE
        if score > 0:
            scored.append((entry, score))

    scored.sort(key=lambda pair: -pair[1])
    return scored


def _detect_service_binaries(text: str, catalog: list[SymptomEntry] | None = None) -> list[str]:
    """`catalog=None` (the v0.6-era default every direct unit test of
    this function still uses) scans against `_ALL_SERVICE_BINARIES`, the
    static CATALOG's own precomputed set. Passing a combined catalog
    (v1.0, see `_combined_catalog`) recomputes the set fresh from it
    instead, so a dynamic entry's service_binaries become recognizable in
    free text immediately, without needing `_ALL_SERVICE_BINARIES` itself
    (a module-load-time constant) to somehow stay in sync with a table
    that changes at runtime.
    """
    text_lower = text.lower()
    binaries = (
        _ALL_SERVICE_BINARIES
        if catalog is None
        else sorted({b for entry in catalog for b in entry["service_binaries"]})
    )
    return [b for b in binaries if b in text_lower or b.replace("-", " ") in text_lower]


def _combined_catalog() -> list[SymptomEntry]:
    """CATALOG (static, hand-reviewed -- adr-0008 decision #1) plus every
    currently-"published" feedback-loop entry (v1.0, adr-0010; see
    openstack_expert_catalog_store.load_published_entries). A fresh DB
    read on every call rather than a cached merge: a newly-published entry
    should be visible to the very next query, not after a process
    restart, and `load_published_entries` already degrades to an empty
    list (i.e. this just becomes CATALOG) on any DB hiccup -- see that
    function's own docstring."""
    return CATALOG + load_published_entries()


# --------------------------------------------------------------------
# Evidence extraction from an upstream diagnosis (chained mode)
# --------------------------------------------------------------------

def _dominant_metric_from_live_data(data: dict) -> str | None:
    """Same "which resource is actually hot" logic as anomaly.py's
    _hypothesize_cause live-threshold tier, reused here because both need
    the same answer to the same question from the same shape of data."""
    candidates = [
        (data.get("cpu_percent", 0.0), "cpu_usage"),
        (data.get("memory_percent", 0.0), "ram_usage"),
        (data.get("disk_percent", 0.0), "disk_usage"),
    ]
    value, name = max(candidates, key=lambda c: c[0])
    return name if value >= _METRIC_TRIGGER_THRESHOLD else None


def _evidence_from_anomaly(raw_data: dict) -> dict:
    metric_signal = raw_data.get("metric_signal") or {}
    log_signal = raw_data.get("log_signal") or {}
    data = metric_signal.get("data") or {}

    metric_name = None
    if metric_signal.get("has_signal"):
        if data.get("source") == "anomaly_flags":
            metric_name = data.get("metric_name")
        else:
            metric_name = _dominant_metric_from_live_data(data)

    log_lines = [e["line"] for e in log_signal.get("entries", [])]
    combined_text = " ".join(log_lines) + " " + (raw_data.get("likely_cause") or "")
    service_binaries = _detect_service_binaries(combined_text)

    evidence_sentences = [metric_signal.get("detail", "")]
    if log_signal.get("has_signal") or log_signal.get("degraded"):
        evidence_sentences.append(log_signal.get("detail", ""))

    return {
        "metric_name": metric_name,
        "service_binaries": service_binaries,
        "log_lines": log_lines,
        "evidence_line": " ".join(s for s in evidence_sentences if s),
        "hostname": raw_data.get("hostname"),
    }


def _evidence_from_monitoring(raw_data: dict) -> dict:
    metrics = raw_data
    if metrics.get("status") != "up":
        # Sentinel matched by the "node-unreachable" catalog entry's own
        # metric_names -- see that entry's comment. A dead host isn't "a
        # resource reading high", it's a different symptom entirely, so
        # this deliberately doesn't fall through to _dominant_metric_from_
        # live_data (which would just see all-zero readings and match
        # nothing, or worse, something misleading).
        metric_name = "host_down"
    else:
        metric_name = _dominant_metric_from_live_data(metrics)

    evidence_line = (
        f"{metrics.get('node', 'this host')} is currently at {metrics.get('cpu_percent')}% CPU, "
        f"{metrics.get('memory_percent')}% RAM, {metrics.get('disk_percent')}% disk -- "
        f"status {metrics.get('status')} ({metrics.get('health')})."
    )
    return {
        "metric_name": metric_name,
        "service_binaries": [],
        "log_lines": [],
        "evidence_line": evidence_line,
        "hostname": metrics.get("node"),
    }


def _evidence_from_network(raw_data: dict) -> dict:
    """network_agent (nodes/network.py) never produces free-text log
    lines the way anomaly.py does -- its checks are structured readings
    (interface counters, Neutron agent/router/network/FIP/port/instance
    status), not a log stream to search for keywords. There's simply
    nothing to put in `log_lines` here, so `_match_symptoms`' keyword-in-
    log-line scoring is a no-op for this source rather than a gap.

    v0.10 (Phase C) branches on `raw_data["scope"]` (added alongside the
    entity-scoped path, see nodes/network.py's module docstring; absent/
    "node" on any pre-Phase-C raw_data, so this stays backward compatible
    with a fixture or trace that predates the scope key):

    - "node" (unchanged v0.9 behavior): `down_agents`' binaries feed
      `service_binaries` the same way anomaly's log-detected binaries do.
      New in Phase C: if there are no down *agents* but `_check_neutron`
      found an instance on this node with its own port down
      (`bad_instances`), that's exactly what the new `port-down`/
      `instance-stuck-in-error` catalog entries exist for -- fed in via
      the same synthetic-metric-name idiom `_evidence_from_monitoring`'s
      `host_down` sentinel already uses, since a down port isn't a real
      Prometheus/anomaly_detector metric any more than "the host itself
      is down" is.
    - "network" / "subnet" / "instance": no agent binaries at all (these
      scopes never look at Neutron *agents*, see network_health.py) --
      the same sentinel idiom carries `entity_signal`'s `down_ports`/
      `down_instances` into the matcher instead.
    """
    scope = raw_data.get("scope", "node")

    if scope != "node":
        entity_signal = raw_data.get("entity_signal") or {}
        down_ports = entity_signal.get("down_ports") or []
        down_instances = entity_signal.get("down_instances") or []
        # An instance actually in ERROR with its own port down is the
        # more specific symptom (instance-stuck-in-error's catalog entry
        # is written for exactly this correlation) -- a bare down port
        # with no ERROR instance attached to it is the more general
        # port-down entry. Checked in this order so the tighter match
        # wins when both are true.
        if any((i or {}).get("status") == "ERROR" for i in down_instances):
            metric_name = "instance_stuck_error"
        elif down_ports:
            metric_name = "port_down"
        else:
            metric_name = None
        return {
            "metric_name": metric_name,
            "service_binaries": [],
            "log_lines": [],
            "evidence_line": entity_signal.get("detail", ""),
            "hostname": None,
        }

    neutron_signal = raw_data.get("neutron_signal") or {}
    metric_signal = raw_data.get("metric_signal") or {}
    down_agents = neutron_signal.get("down_agents") or []
    bad_instances = neutron_signal.get("bad_instances") or []
    service_binaries = [a["binary"] for a in down_agents if a.get("binary")]

    metric_name = None
    if not service_binaries and bad_instances:
        error_instances = [i for i in bad_instances if i.get("status") == "ERROR"]
        metric_name = "instance_stuck_error" if error_instances else "port_down"

    evidence_sentences = [metric_signal.get("detail", ""), neutron_signal.get("detail", "")]
    return {
        "metric_name": metric_name,
        "service_binaries": service_binaries,
        "log_lines": [],
        "evidence_line": " ".join(s for s in evidence_sentences if s),
        "hostname": raw_data.get("hostname"),
    }


def should_trigger_after_anomaly(state: CortexState) -> bool:
    """Whether anomaly_agent's result has anything for this agent to
    explain -- called from graph.py's conditional edge, and mirrors what
    this module's own chained path checks internally (see
    _evidence_from_anomaly / the "no positive match" fallback in
    _run_chained) so a "yes, chain" decision here is never followed by
    "actually, nothing to say" once inside the node.
    """
    if state.get("error") or not state.get("agent_result"):
        return False
    raw_data = state["agent_result"]["raw_data"]
    metric_signal = raw_data.get("metric_signal") or {}
    log_signal = raw_data.get("log_signal") or {}
    return bool(metric_signal.get("has_signal") or log_signal.get("has_signal") or log_signal.get("degraded"))


def should_trigger_after_monitoring(state: CortexState) -> bool:
    """Whether monitoring_agent's live read looks concerning enough to
    walk through -- same "status not up, health not healthy" bar
    monitoring's own system prompt already uses for "call this out", so
    chaining fires exactly when a human reading the monitoring answer
    would already feel like something's wrong.
    """
    if state.get("error") or not state.get("agent_result"):
        return False
    metrics = state["agent_result"]["raw_data"]
    if metrics.get("scope") == "multi":
        # A fleet answer has no single host's status/health to walk through
        # (and _evidence_from_monitoring expects exactly that shape) -- the
        # per-node table already says which nodes need attention.
        return False
    return metrics.get("status") != "up" or metrics.get("health") != "healthy"


def should_trigger_after_network(state: CortexState) -> bool:
    """Whether network_agent's finding has anything for this agent to
    explain -- same shape as should_trigger_after_anomaly: fires whenever
    network_agent's checks found something, and leaves it to
    `_match_symptoms` to decide whether that something is specific enough
    to actually match a catalog entry (see `_run_chained`'s "no positive
    match -> leave upstream diagnosis as the final answer").

    v0.10 (Phase C) branches on `raw_data["scope"]` the same way
    `_evidence_from_network` does: "node" (default, pre-Phase-C shape)
    fires on a nonzero error/drop rate or a Neutron agent/router/network/
    FIP/instance-port issue; the entity-scoped kinds have no metric_signal
    at all, so they fire on `entity_signal` alone.
    """
    if state.get("error") or not state.get("agent_result"):
        return False
    raw_data = state["agent_result"]["raw_data"]
    scope = raw_data.get("scope", "node")

    if scope != "node":
        entity_signal = raw_data.get("entity_signal") or {}
        return bool(entity_signal.get("has_signal") or entity_signal.get("degraded"))

    metric_signal = raw_data.get("metric_signal") or {}
    neutron_signal = raw_data.get("neutron_signal") or {}
    return bool(
        metric_signal.get("has_signal")
        or neutron_signal.get("has_signal")
        or neutron_signal.get("degraded")
    )


# --------------------------------------------------------------------
# Rendering: SymptomEntry -> the fixed 3-layer answer text
# --------------------------------------------------------------------

def _fill_hostname(command: str, hostname: str | None) -> str:
    if not hostname:
        return command
    return _HOST_PLACEHOLDERS.sub(hostname, command)


def _render_command_list(commands: list[dict], hostname: str | None) -> str:
    """Renders each command as its own bullet, with the description as the
    bullet's lead-in and the command itself in a fenced ```bash block --
    the fence is what actually gets the client's markdown renderer to draw
    a proper copyable code block instead of one long inline-code line, and
    the (read-only)/(state-changing) label stays plain text (not inside
    the fence) so it's still readable as a UI-parseable tag rather than
    part of the shell command."""
    blocks = []
    for cmd in commands:
        label = "read-only" if cmd["read_only"] else "state-changing"
        command_text = _fill_hostname(cmd["command"], hostname)
        blocks.append(
            f"- **{cmd['description']}** _({label})_\n"
            f"  ```bash\n"
            f"  {command_text}\n"
            f"  ```"
        )
    return "\n".join(blocks)


def _render_answer(entry: SymptomEntry, evidence_line: str, hostname: str | None) -> str:
    what_happening = f"{evidence_line} {entry['what_it_means']}".strip()
    confirm_block = _render_command_list(entry["confirm_commands"], hostname)
    remediate_block = _render_command_list(entry["remediation_commands"], hostname)

    return (
        f"### {entry['title']}\n\n"
        f"#### What's happening\n{what_happening}\n\n"
        f"#### How to confirm it yourself\n{confirm_block}\n\n"
        f"#### What's usually done about it\n{remediate_block}\n\n"
        f"---\n"
        f"**Deeper reference:** {entry['doc_ref']}"
    )


def _no_match_standalone_answer(query: str) -> str:
    return (
        "I don't have a specific runbook entry that matches that yet. The OpenStack Expert "
        "catalog currently covers:\n\n"
        "- Host resource pressure (CPU / RAM / disk)\n"
        "- The core Nova, Cinder, and Neutron service agents\n"
        "- libvirt / hypervisor issues\n"
        "- RabbitMQ, MariaDB, and Keystone problems\n"
        "- Glance image issues\n\n"
        "Try naming the specific symptom or service (e.g. \"nova-compute\", \"neutron-l3-agent\", "
        "\"disk full\"), or ask it as a general documentation question and I'll search the "
        "knowledge base instead."
    )


def _to_command_dicts(commands: list[dict], hostname: str | None) -> list[dict]:
    """The same commands rendered into `summary`, structured for raw_data
    so a frontend can render read-only/state-changing distinctly (an icon,
    a confirmation dialog before copying a state-changing one) without
    re-parsing the markdown."""
    return [
        {**cmd, "command": _fill_hostname(cmd["command"], hostname)}
        for cmd in commands
    ]


def _build_result(entry: SymptomEntry, evidence_line: str, hostname: str | None, extra_raw: dict) -> dict:
    return {
        "summary": _render_answer(entry, evidence_line, hostname),
        "confidence": 0.85 if evidence_line else 0.6,
        "raw_data": {
            "matched_symptom_id": entry["id"],
            "matched_symptom_title": entry["title"],
            "category": entry["category"],
            "confirm_commands": _to_command_dicts(entry["confirm_commands"], hostname),
            "remediation_commands": _to_command_dicts(entry["remediation_commands"], hostname),
            "doc_ref": entry["doc_ref"],
            # v1.0: same "source" label the fallback tiers use (see
            # _build_docs_fallback_result / _build_web_fallback_result /
            # _standalone_fallback's final tier) so a frontend can render
            # a citation badge the same way regardless of which tier
            # produced the answer, without inferring it from whether
            # matched_symptom_id is set.
            "source": "catalog",
            **extra_raw,
        },
    }


# --------------------------------------------------------------------
# v1.0 (adr-0010): standalone-only fallback tiers, tried in order when
# _match_symptoms finds nothing in the combined catalog -- official
# OpenStack docs, then a community web search, then finally the original
# v0.6 "no runbook entry" text. See the module docstring's v1.0 section
# for why this is standalone-only (chained no-match keeps its v0.6
# behavior of leaving the upstream diagnosis unmodified).
# --------------------------------------------------------------------

_MIN_EXCERPT_CHARS = 200


def _callout(kind: str, body: str) -> str:
    """GitHub-style admonition blockquote -- the web client's Markdown
    renderer turns `> [!WARNING]` / `> [!NOTE]` into a small colored callout
    (components/CopilotAgentPanels.tsx). Plain blockquote elsewhere."""
    lines = body.strip().splitlines()
    return f"> [!{kind}]\n" + "\n".join(f"> {ln}" for ln in lines)


def _render_docs_fallback(query: str, hits: list[DocResult]) -> str:
    rendered = []
    for hit in hits:
        excerpt = doc_text_to_markdown(hit.text, hit.heading)
        rendered.append((hit, excerpt))
    # A hit that is just a heading plus one intro sentence adds noise next to
    # a substantive one -- drop it unless it is all we have.
    substantive = [(h, e) for h, e in rendered if len(e) >= _MIN_EXCERPT_CHARS]
    rendered = substantive or rendered

    sections = []
    for n, (hit, excerpt) in enumerate(rendered, start=1):
        title = clean_inline(hit.doc_title)
        heading = clean_inline(hit.heading or "")
        label = f"{title} — {heading}" if heading and heading != title else title
        sections.append(
            f"#### {n}. {label}\n\n{excerpt}\n\n[Open in docs.openstack.org]({hit.source_url})"
        )
    return (
        f"### From official OpenStack documentation\n\n"
        + "\n\n".join(sections)
        + "\n\n---\n"
        + _callout(
            "NOTE",
            "**Source (official docs):** the excerpts above are from docs.openstack.org, not "
            "this deployment's curated catalog -- confirm they apply to your setup before acting.",
        )
    )


def _build_docs_fallback_result(query: str, hits: list[DocResult]) -> dict:
    return {
        "summary": _render_docs_fallback(query, hits),
        "confidence": 0.5,
        "raw_data": {
            "matched_symptom_id": None,
            "source": "official_docs",
            "query": query,
            "doc_results": [
                {
                    "title": clean_inline(h.doc_title),
                    "heading": clean_inline(h.heading) if h.heading else None,
                    "url": h.source_url,
                    "score": h.score,
                    # The raw excerpt is the evidence the summary was built
                    # from -- kept here so critic.py's numeric-grounding
                    # check sees it (otherwise every UUID/port number quoted
                    # from the docs looked "ungrounded").
                    "text": h.text,
                }
                for h in hits
            ],
        },
    }


def _render_web_fallback(query: str, hits: list[WebSearchResult]) -> str:
    lines = [f"- [{h.title}]({h.url})" + (f" — {h.snippet}" if h.snippet else "") for h in hits]
    return (
        f"### Community-sourced results (unverified)\n\n"
        + _callout(
            "WARNING",
            f'No catalog entry or official documentation matches "{query}" -- here\'s what turned '
            f"up in the OpenStack community (Launchpad, mailing lists, Q&A). This is **not** "
            f"official documentation and hasn't been reviewed -- verify anything here before "
            f"acting on it.",
        )
        + "\n\n"
        + "\n".join(lines)
        + "\n\n---\n"
        + "**Source:** community web search -- not docs.openstack.org, and not this "
        "deployment's curated catalog."
    )


def _build_web_fallback_result(query: str, hits: list[WebSearchResult]) -> dict:
    return {
        "summary": _render_web_fallback(query, hits),
        "confidence": 0.3,
        "raw_data": {
            "matched_symptom_id": None,
            "source": "web_search",
            "query": query,
            "web_results": [{"title": h.title, "url": h.url, "snippet": h.snippet} for h in hits],
        },
    }


def _standalone_fallback(query: str) -> dict:
    """Tries official docs, then a community web search, before finally
    giving up. Each tier is wrapped broadly: a missing TAVILY_API_KEY, an
    unreachable Qdrant Cloud cluster, or an embedding model that can't
    load are all just "this tier isn't available right now" -- never a
    crash, and never something that blocks trying the next tier or
    falling back to the original v0.6 text. See services/openstack_docs/
    search.py and services/web_search.py's own docstrings for what each
    tier is grounded in and why they're kept visibly distinct."""
    try:
        docs_hits = search_official_docs(query, top_k=3)
    except Exception:
        logger.info("openstack_expert: official-docs fallback unavailable", exc_info=True)
        docs_hits = []

    # Table-of-contents / navigation chunks are semantically close to almost
    # any question but contain no answer -- drop them so the next tier gets a
    # chance instead of showing a wall of link titles as "documentation".
    docs_hits = [h for h in docs_hits if not looks_like_index(h.text)]

    if docs_hits:
        return _build_docs_fallback_result(query, docs_hits)

    try:
        web_hits = run_web_search(query, max_results=5)
    except Exception:
        logger.info("openstack_expert: web-search fallback unavailable", exc_info=True)
        web_hits = []

    if web_hits:
        return _build_web_fallback_result(query, web_hits)

    return {
        "summary": _no_match_standalone_answer(query),
        "confidence": 0.2,
        "raw_data": {"matched_symptom_id": None, "source": "none", "query": query},
    }


# --------------------------------------------------------------------
# The two entry paths
# --------------------------------------------------------------------

def _run_chained(state: CortexState, upstream: str, catalog: list[SymptomEntry]) -> CortexState:
    upstream_result = state["agent_result"]
    raw_data = upstream_result["raw_data"]

    if upstream == "anomaly":
        evidence = _evidence_from_anomaly(raw_data)
    elif upstream == "network":
        evidence = _evidence_from_network(raw_data)
    else:
        evidence = _evidence_from_monitoring(raw_data)

    matches = _match_symptoms(
        metric_name=evidence["metric_name"],
        service_binaries=evidence["service_binaries"],
        query=state["user_query"],
        log_lines=evidence["log_lines"],
        catalog=catalog,
    )

    if not matches:
        # should_trigger_after_* already confirmed there's *something*
        # anomalous, but nothing in the catalog recognizes this specific
        # pattern -- leave the upstream diagnosis as the answer rather
        # than forcing a generic, unhelpful "teaching" layer on top of it.
        logger.info(
            "openstack_expert: chained from %s but no catalog entry matched, "
            "leaving upstream diagnosis as the final answer", upstream,
        )
        return state

    entry, _score = matches[0]
    result = _build_result(
        entry,
        evidence["evidence_line"],
        evidence["hostname"],
        extra_raw={"diagnosed_by": upstream, "upstream_summary": upstream_result["summary"]},
    )
    state["agent_result"] = result
    state["target_agent"] = "openstack_expert"
    return state


def _run_standalone(state: CortexState, catalog: list[SymptomEntry]) -> CortexState:
    query = state["user_query"]
    known_nodes = state.get("known_nodes") or []

    service_binaries = _detect_service_binaries(query, catalog=catalog)
    matches = _match_symptoms(query=query, service_binaries=service_binaries, catalog=catalog)

    # Best-effort only -- a standalone "how do I check nova-compute"
    # question doesn't need a specific host, but if one's clearly named
    # (the same resolver every other agent uses), commands get filled in
    # with it rather than left as a placeholder.
    node = resolve_node(query, known_nodes) if known_nodes else None
    hostname = node["hostname"] if node else None

    if not matches:
        # v1.0: no longer immediately the static "no runbook entry" text --
        # see _standalone_fallback and the module docstring's v1.0 section.
        state["agent_result"] = _standalone_fallback(query)
        state["error"] = None
        return state

    entry, _score = matches[0]
    result = _build_result(entry, evidence_line="", hostname=hostname, extra_raw={"diagnosed_by": None})
    state["agent_result"] = result
    state["error"] = None
    return state


def openstack_expert_agent(state: CortexState) -> CortexState:
    # v1.0: built once per call so both paths below see the same snapshot
    # of static-plus-published entries -- see _combined_catalog's own
    # docstring for why this is a fresh read rather than a cached one.
    catalog = _combined_catalog()
    upstream = state.get("target_agent")
    if upstream in ("anomaly", "monitoring", "network") and state.get("agent_result") and not state.get("error"):
        return _run_chained(state, upstream, catalog)
    return _run_standalone(state, catalog)
