[controllers]
controller ansible_host=10.0.1.10 ansible_user=root node_role=controller

[computes]
compute1 ansible_host=10.0.1.2 ansible_user=root node_role=compute
compute2 ansible_host=10.0.1.4 ansible_user=root node_role=compute

[storages]
storage ansible_host=10.0.2.3 ansible_user=root node_role=storage

# All nodes that must run node_exporter
[monitoring:children]
controllers
computes
storages

# Where Prometheus itself runs (controller, same as Horizon/HAProxy)
[prometheus_server]
controller


[all:vars]
node_exporter_version=1.8.2
node_exporter_archive=node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz