"""initial

Revision ID: 72b4f64486a0
Revises: 
Create Date: 2026-07-24 08:42:03.603157

"""
from alembic import op
import sqlalchemy as sa


revision = '72b4f64486a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('exporter_port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('controller','compute','storage','monitoring')", name='ck_nodes_role_allowed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('ip_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    # ### end Alembic commands ###
