"""improve metric baseline model

Revision ID: dcafc2bcc19f
Revises: f0a38ce4eb49
Create Date: 2026-08-03 13:30:22.197826

"""
from alembic import op
import sqlalchemy as sa


revision = 'dcafc2bcc19f'
down_revision = 'f0a38ce4eb49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_baselines', sa.Column('mean', sa.Float(), nullable=False))
    op.add_column('metric_baselines', sa.Column('stddev', sa.Float(), nullable=False))
    op.add_column('metric_baselines', sa.Column('median', sa.Float(), nullable=False))
    op.add_column('metric_baselines', sa.Column('mad', sa.Float(), nullable=False))
    op.drop_column('metric_baselines', 'baseline_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_baselines', sa.Column('baseline_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('metric_baselines', 'mad')
    op.drop_column('metric_baselines', 'median')
    op.drop_column('metric_baselines', 'stddev')
    op.drop_column('metric_baselines', 'mean')
    # ### end Alembic commands ###
