"""create metric baselines

Revision ID: f0a38ce4eb49
Revises: 73a1d67453e1
Create Date: 2026-08-03 10:11:40.057618

"""
from alembic import op
import sqlalchemy as sa


revision = 'f0a38ce4eb49'
down_revision = '73a1d67453e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hour >= 0 AND hour <= 23', name='ck_metric_baselines_hour'),
    sa.CheckConstraint('sample_count >= 0', name='ck_metric_baselines_sample_count'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_metric_baselines_weekday'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'metric_name', 'weekday', 'hour', name='uq_metric_baseline_slot')
    )
    op.create_index('ix_metric_baselines_lookup', 'metric_baselines', ['node_id', 'metric_name', 'weekday', 'hour'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_baselines_lookup', table_name='metric_baselines')
    op.drop_table('metric_baselines')
    # ### end Alembic commands ###
